version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.rails
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    tty: true
  
  db:
    image: postgres:13
    ports:
      - 5432:5432  # mapeo host:5433 a container:5432 (postgresql)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sapphiron-dev
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

volumes:
  postgres_data:
